<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW2wAtk1\appAppKernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW2wAtk1/appAppKernelProdContainer.php') {
    touch(__DIR__.'/ContainerW2wAtk1.legacy');

    return;
}

if (!\class_exists(appAppKernelProdContainer::class, false)) {
    \class_alias(\ContainerW2wAtk1\appAppKernelProdContainer::class, appAppKernelProdContainer::class, false);
}

return new \ContainerW2wAtk1\appAppKernelProdContainer([
    'container.build_hash' => 'W2wAtk1',
    'container.build_id' => '242ba8c2',
    'container.build_time' => 1721044164,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW2wAtk1');
